name = "dua"
version = "2.37.0"
abi = "riscv64gc-linux-musl"

[source]
git = "https://github.com/Byron/dua-cli"
rev = "v2.37.0"

[entrypoint]
argv = ["dua"]
env = { }

[maintainer]
name = "userland.run"
contact = "https://github.com/userland-run/catalog"

[status]
features = ["catalog.recipe.dua"]
