name = "task"
version = "3.51.1"
abi = "riscv64gc-linux-musl"

[source]
git = "https://github.com/go-task/task"
rev = "v3.51.1"

[entrypoint]
argv = ["task"]
env = { }

[maintainer]
name = "userland.run"
contact = "https://github.com/userland-run/catalog"

[status]
features = ["catalog.recipe.task"]
