name = "bat"
version = "0.26.1"
abi = "riscv64gc-linux-musl"

[source]
git = "https://github.com/sharkdp/bat"
rev = "v0.26.1"

[entrypoint]
argv = ["bat"]
env = { }

[bundle]
topics = ["Text"]

[maintainer]
name = "userland.run"
contact = "https://github.com/userland-run/catalog"

[status]
features = ["catalog.recipe.bat"]
