name = "frawk"
version = "0.4.7"
abi = "riscv64gc-linux-musl"

[source]
git = "https://github.com/ezrosent/frawk"
rev = "v0.4.7"

[entrypoint]
argv = ["frawk"]
env = { }

[bundle]
topics = ["Data"]

[maintainer]
name = "userland.run"
contact = "https://github.com/userland-run/catalog"

[status]
features = ["catalog.recipe.frawk"]
