name = "rage"
version = "0.11.2"
abi = "riscv64gc-linux-musl"

[source]
git = "https://github.com/str4d/rage"
rev = "v0.11.2"

[entrypoint]
argv = ["rage"]
env = { }

[bundle]
topics = ["Encryption"]

[maintainer]
name = "userland.run"
contact = "https://github.com/userland-run/catalog"

[status]
features = ["catalog.recipe.rage"]
